apiVersion: batch/v1
kind: CronJob
metadata:
  name: teleray
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    job: teleray
spec:
  schedule: "{{ .Values.cron }}"
  jobTemplate:
    spec:
      template: 
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: DB_URL
                  value: "{{ .Values.database.url }}/{{ .Values.database.name }}"
                - name: TTL
                  value: "{{ .Values.database.ttl }}" 
                - name: CRON
                  value: ""            
                - name: DEBUG
                  value: "{{ .Values.debug }}"
          restartPolicy: OnFailure
